### ISSUE TITLE
Support for advanced .refine

### ISSUE THREAD

**Issue by flavianh** [DavidTimms/zod-fast-check#11]
Hello,

I am trying to use a schema with a `refine` function too specific to resolve a given function.
I've tried to use `override` but I would end up having to recreate the whole structure of my schema's object (my schema is quite large, and I'm using zod-fast-check to avoid this tedious work). With the current API, can we override the arbitrary generation to be able to set the right value ranges for it to work?

```
const simpleRefineSchema = z
  .object({
    name: z.string(),
    wltpElectricConsumption: z.number().safe(),
  })
  .refine(
    (schema) => schema.name.startswith("test") && schema.wltpElectricConsumption > 0 || schema.name.startswith("other")
  );
const simpleRefineArbitrary = ZodFastCheck().inputOf(simpleRefineSchema);
```

ends up with

```
Unable to generate valid values for Zod schema. An override is must be provided for the schema at path '.'.
```

So far my countermeasure is to split the schema into two parts: one with the object, and one with the refinement. I would still like to find a better solution where I can guide the arbitrary into generating the right values.

Thanks

**Comment by flavianh** [comment]
After giving it more thought, I figured that I could also bypass the problem by unwrapping the ZodEffets.

```typescript
type UnwrapZodEffects<T extends ZodTypeAny> = T extends ZodEffects<
  infer U extends ZodTypeAny
>
  ? UnwrapZodEffects<U>
  : T;

export function unwrapZodEffects<T extends ZodEffects<ZodTypeAny>>(
  zodEffects: T
): UnwrapZodEffects<T> {
  const innerType = zodEffects.innerType();
  if (innerType instanceof ZodEffects) {
    return unwrapZodEffects(
      innerType as ZodEffects<ZodTypeAny>
    ) as UnwrapZodEffects<T>;
  }

  return zodEffects.innerType() as UnwrapZodEffects<T>;
}

const simpleRefineArbitrary = ZodFastCheck().inputOf(
  unwrapZodEffects(simpleRefineSchema)
);
```

**Comment by DavidTimms** [comment]
Hi Flavian,

unwrapping the effects will work, but there is a potentially simpler way. If you override just the name property, it should be able to generate values for the schema:

```ts
const simpleRefineArbitrary =
    ZodFastCheck()
    .override(
        simpleRefineSchema.innerType().shape.name,
        fc.string().chain(s => fc.constantFrom("test", "other").map(prefix => prefix + s))
    )
    .inputOf(simpleRefineSchema);
```
