### ISSUE TITLE
Question: Is this library still maintained?

### ISSUE THREAD

**Issue by Kawacrepe** [DavidTimms/zod-fast-check#6]
I've been looking to use fast-check & zod in different projects.

Is this library still maintained ? Do you need help?

**Comment by IamBlueSlime** [comment]
@DavidTimms Just doing a bump here, there are two great PRs just waiting for your approval!

**Comment by DavidTimms** [comment]
Hi guys, sorry for the delayed response. I haven't had much time to look at this library recently.

I should be able to look at the PRs and get a new version out in the next few days which is supports fast-check 3.

**Comment by fwoelffel** [comment]
Hi @DavidTimms 👋 Almost a couple years later, I come up with the same question. Perhaps you'd like some help to maintain this project? If so let my know.
