### ISSUE TITLE
Support Zod 3.20

### ISSUE THREAD

**Issue by DavidTimms** [DavidTimms/zod-fast-check#8]
The new version of Zod brings new schema features which will need corresponding support in zod-fast-check.

https://github.com/colinhacks/zod/releases/tag/v3.20

**Comment by DavidTimms** [comment]
The newly released version 0.9.0 add support for the new `.pipe` and `.catch` methods. A later release will add support for `z.symbol()`, `z.string().datetime()` and `z.number().finite()`.

**Comment by DavidTimms** [comment]
Hi Deniz. Which of the unsupported features are you using? I can prioritise adding support for that.

**Comment by denizdogan** [comment]
> Hi Deniz. Which of the unsupported features are you using? I can prioritise adding support for that.

Hi! Thanks a lot, that would be awesome! It's primarily `pipe` that I'm making heavy use of right now.

**Comment by DavidTimms** [comment]
`pipe` should be supported by the zod-fast-check 0.9. If it isn't, could you provide examples of one of your schemas?

**Comment by denizdogan** [comment]
@DavidTimms Sorry, I missed your other comment about `.pipe` working now! Sorry for the noise.

**Comment by DavidTimms** [comment]
This is resolved with the release of [zod-fast-check 0.10.0](https://github.com/DavidTimms/zod-fast-check/releases/tag/v0.10.0).
